import { BasicLayoutProps } from '@ant-design/pro-layout';

const layout: BasicLayoutProps = {
  title: 'Components',
  logo: '/react-components/assets/react.ico',
  // pure: false,
  // loading: true,
  // menuHeaderRender,
  // onMenuHeaderClick,
  // contentStyle: {
  //   // minHeight: 'calc(100vh - 48px - 124px)',
  //   // padding: 24,
  // },
  // layout: 'mix',
  // splitMenus: true,
  // contentWidth: 'Fluid',
  // navTheme: 'realDark',
  // fixedHeader: false,
  // fixSiderbar: true,
  // breakpoint: 'lg',
  menu: { locale: true },
  // iconfontUrl: '//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js',
  locale: 'zh-CN',
  siderWidth: 208,
  // siderWidth: 240,
  // onCollapse,
  // onPageChange,
  // headerRender,
  // headerTitleRender,
  // headerContentRender,
  // rightContentRender,
  // collapsedButtonRender,
  // footerRender,
  // pageTitleRender,
  // menuRender,
  // postMenuData,
  // menuItemRender,
  // subMenuItemRender,
  // menuDataRender,
  // breadcrumbRender,
  // route,
  // disableMobile,
  // links,
  // menuProps,
};

export default layout;
